# Welcome to Jekyll!

# Website settings
title: "木偶人"
description: "木偶人技术博客，使用Jekyll与Github Pages"
keywords: "木偶人,胡登军,Simon,simonhoo,java,oracle,thrift,go,blog,Jekyll,github,gh-pages"
icp: "粤ICP备14028579号"

baseurl: "/"
url: "http://www.cottsoft.com"
# url: "http://127.0.0.1:4000"

# author
author:
  name: '木偶人'
  first_name: 'Hoo'
  last_name: 'Simon'
  email: 'simon@cottsoft.com'
  facebook_username: 'simonhoo'
  github_username: 'simonhoo'
  head_img: 'static/img/simonhoo/simonhoo.png'

# social link
contact:
  first_name: 'Hoo'
  last_name: 'Simon'
  description: '有事您说话！'
  website: 'http://wwww.cottsoft.com'
  email: 'simon@cottsoft.com'
  qq: '9930323'
  weixin: 'Dengjun_Hu'
  mobile: '18588224400'

# landing page
landing:
  home: '主页'
  about: '关于'
  career: '职业生涯'
  skills: '技能'
  projects: '开源项目'
  blog: '博客'
  contact: '联系我'

# my projects
project:
  thrift-framework:
    name: 'thrift-framework'
    url: '/simonhoo/thrift-framework'
    img: 'static/img/projects/thrift-framework.jpg'
  thrift-script:
    name: 'thrift-script'
    url: '/simonhoo/thrift-script'
    img: 'static/img/projects/thrift-script.jpg'
  SeaweedFS-Client:
    name: 'SeaweedFS-Client'
    url: '/simonhoo/SeaweedFS-Client'
    img: 'static/img/projects/SeaweedFS-Client.jpg'
  iFramework:
    name: 'iFramework'
    url: '/simonhoo/iFramework'
    img: 'static/img/projects/iFramework.jpg'
  eclipse-plugins:
    name: 'eclipse-plugins'
    url: '/simonhoo/eclipse-plugins'
    img: 'static/img/projects/eclipse-plugins.jpg'
  redspider:
    name: 'redspider'
    url: '/simonhoo/redspider'
    img: 'static/img/projects/redspider.jpg'

# blog index
index:
  home: '首页'
  architecture: '架构与方案'
  pm: '项目管理'
  java: 'Java'
  python: 'Python'
  golang: 'Go'
  database: '数据库'
  os: '操作系统'
  cloud: '云/大数据'
  life: '生活点滴'

# donate
donate:
  weixin: 'static/img/pay/weixin.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  # name: jalpc
  # public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 7c259b91-c2da-4777-8b2a-d70631aba974

# baidu analytics
ba:
  uuid: b7399c3275faaaa7e3edba857b5a23ea

# google analytics
ga:
  #id: UA-73784599-1

# blog img path
img_path: '/static/img/blog'

# Build settings
encoding: "utf-8"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
